steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-central1-docker.pkg.dev/dalvacationhome-429314/dalvacationhome/dalvacationhome-sdp36:latest', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/dalvacationhome-429314/dalvacationhome/dalvacationhome-sdp36:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dalvacationhome-sdp36'
      - '--image'
      - 'us-central1-docker.pkg.dev/dalvacationhome-429314/dalvacationhome/dalvacationhome-sdp36:latest'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
options:
  logging: CLOUD_LOGGING_ONLY
